<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>傻逼刘思玄</title>
<style type="text/css">
.lsx {
	text-align: right;
}
.lsx {
	font-size: 24px;
	text-align: right;
}
</style>
</head>

<body>
<p>没有啥事情</p>
<p>就是想 <strong class="lsx">吃柠檬</strong></p>
<hr />
    <span class="lsx">2019.7.16</span>
</body>
</html>
